[package]
name = "mersenne-prime-number-finder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mersenne-prime-number-miller-rabin = "0.1.0"
clap = "~2.27.0"
num-bigint = "0.4"
num-traits = "0.2"